<?php 
$_aClassFiles = array( 
    "CustomTranslationFiles_Bootstrap"=> CustomTranslationFiles_Registry::$sDirPath . "/include/CustomTranslationFiles_Bootstrap.php", 
    "CustomTranslationFiles_Loader_Main"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/CustomTranslationFiles_Loader_Main.php", 
    "CustomTranslationFiles_Setter"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/CustomTranslationFiles_Setter.php", 
    "CustomTranslationFiles_AdminPage"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/CustomTranslationFiles_AdminPage.php", 
    "CustomTranslationFiles_AdminPage___CustomUploadFileTypes"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/CustomTranslationFiles_AdminPage___CustomUploadFileTypes.php", 
    "CustomTranslationFiles_AdminPage__Page_Setting"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/CustomTranslationFiles_AdminPage__Page_Setting.php", 
    "CustomTranslationFiles_AdminPage__FormSection_Delete"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/data/CustomTranslationFiles_AdminPage__FormSection_Delete.php", 
    "CustomTranslationFiles_AdminPage__FormSection_DoReset"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/data/CustomTranslationFiles_AdminPage__FormSection_DoReset.php", 
    "CustomTranslationFiles_AdminPage__FormSection_Export"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/data/CustomTranslationFiles_AdminPage__FormSection_Export.php", 
    "CustomTranslationFiles_AdminPage__FormSection_Import"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/data/CustomTranslationFiles_AdminPage__FormSection_Import.php", 
    "CustomTranslationFiles_AdminPage__InPageTab_Data"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/data/CustomTranslationFiles_AdminPage__InPageTab_Data.php", 
    "CustomTranslationFiles_AdminPage__FormSection_Sample"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/general/CustomTranslationFiles_AdminPage__FormSection_Sample.php", 
    "CustomTranslationFiles_AdminPage__InPageTab_General"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/general/CustomTranslationFiles_AdminPage__InPageTab_General.php", 
    "CustomTranslationFiles_AdminPage__FormSection_Item"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/item/CustomTranslationFiles_AdminPage__FormSection_Item.php", 
    "CustomTranslationFiles_AdminPage__InPageTab_Item"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/setting/item/CustomTranslationFiles_AdminPage__InPageTab_Item.php", 
    "CustomTranslationFiles_AdminPage__Element_Base"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/_abstract/CustomTranslationFiles_AdminPage__Element_Base.php", 
    "CustomTranslationFiles_AdminPage__FormSection_Base"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/_abstract/CustomTranslationFiles_AdminPage__FormSection_Base.php", 
    "CustomTranslationFiles_AdminPage__InPageTab_Base"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/_abstract/CustomTranslationFiles_AdminPage__InPageTab_Base.php", 
    "CustomTranslationFiles_AdminPage__Page_Base"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/admin/_abstract/CustomTranslationFiles_AdminPage__Page_Base.php", 
    "CustomTranslationFiles_Option"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/option/CustomTranslationFiles_Option.php", 
    "CustomTranslationFiles_Option_Base"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/option/CustomTranslationFiles_Option_Base.php", 
    "CustomTranslationFiles_Debug"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/utility/CustomTranslationFiles_Debug.php", 
    "CustomTranslationFiles_PluginUtility"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/utility/CustomTranslationFiles_PluginUtility.php", 
    "CustomTranslationFiles_Utility"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/utility/CustomTranslationFiles_Utility.php", 
    "CustomTranslationFiles_WPUtility"=> CustomTranslationFiles_Registry::$sDirPath . "/include/main/utility/CustomTranslationFiles_WPUtility.php", 
);
